### ISSUE TITLE
Add default toleration to worker pod

### ISSUE THREAD

**Issue by dsludwig** [dask/dask-kubernetes#109]
I have setup an instance of dask-kubernetes that uses taints to prevent `kube-system` components from scheduling onto the nodes. This really helps when using Google's autoscaler, since empty nodes are easily batch deleted.

The configuration that I needed to add is here:
https://github.com/pangeo-data/atmos.pangeo.io-deploy/blob/0ddab66e1a37f9f2a9ac85c8fdad7301b9e3882d/deployments/atmos.pangeo.io/image/.dask/config.yaml#L36-L44
```
      tolerations:
      - key: "k8s.dask.org_dedicated"
        operator: "Equal"
        value: "worker"
        effect: "NoSchedule"
      - key: "k8s.dask.org/dedicated"
        operator: "Equal"
        value: "worker"
        effect: "NoSchedule"
```

It might be nice to add a default toleration, so we standardize what taints are recommended for using dask-kubernetes.
