### ISSUE TITLE
dask-scheduler pod incompatible version with dask-worker

### ISSUE THREAD

**Issue by Waterdrips** [dask/dask-kubernetes#161]
I am running `helm install --name dask-prefect -f config.yaml stable/dask` on a Docker for Mac Kubernetes cluster the logs for the `dask-scheduler` pod show a type error:

```
+ '[' '' ']'
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
no environment.yml
+ '[' '' ']'
+ '[' '' ']'
+ dask-scheduler --port 8786 --bokeh-port 8787
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:     tcp://10.1.72.61:8786
distributed.scheduler - INFO -       bokeh at:                     :8787
distributed.scheduler - INFO - Local Directory:    /tmp/scheduler-s7rdwr2l
distributed.scheduler - INFO - -----------------------------------------------
distributed.core - ERROR - add_worker() got an unexpected keyword argument 'types'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 346, in handle_comm
    result = yield result
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
TypeError: add_worker() got an unexpected keyword argument 'types'
```

My config.yaml is 
```
# config.yaml
worker:
  replicas: 1
  resources:
    limits:
      cpu: 1
      memory: 1.5G
    requests:
      cpu: 1
      memory: 1.5G
  env:
    - name: EXTRA_PIP_PACKAGES
      value: requests pysftp prefect --upgrade

jupyter:
  enabled: false
```

A closed issue dask/dask/issues/4998 in the dask/dask repo seems to point at differing distributed versions. 

Anyone have any pointers?

**Comment by mrocklin** [comment]
This sounds like a version mismatch issue.  I recommend verifying that the
versions of the dask and distributed packages are the same.

**Comment by Waterdrips** [comment]
on the scheduler container: 
```
distributed               1.25.2                py37_1000    conda-forge
dask                      1.1.0                      py_1    conda-forge
dask-core                 1.1.0                      py_0    conda-forge
```

on the worker: 
```
distributed               1.28.1                   pypi_0    pypi
dask                      1.1.0                      py_1    conda-forge
dask-core                 1.1.0                      py_0    conda-forge
```

so yes - looks like that. 

Looking at the source of the packages above made me look back at the config.yaml extra_pip_packages, turns out prefect installs the latest version of distributed... 

This is going to cause me issues - but its my issue to overcome. 

Thanks for the pointer.

**Comment by Waterdrips** [comment]
For anyone who finds this and wants a quick workaround, I got this working by installing prefect on the scheduler too using the config.yaml to bring both versions up to 1.28.1


```
scheduler:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: prefect
```
