### ISSUE TITLE
Slow S3 access in worker pods

### ISSUE THREAD

**Issue by system123** [dask/dask-kubernetes#174]
I have geotiff data stored in an S3 bucket which I am reading using XArray and processing via Dask. If I run my script using a LocalCluster the entire process of reading from the S3 bucket and computing the mean of the data takes in the order of 40 seconds. However, if I launch a KubeCluster with a single worker and run the mean computation on there the computation takes around 8 minutes as the data rate from S3 is significantly slower. 

The script I am running is:
```
import xarray as xr
from glob import glob
from dask.distributed import Client, LocalCluster, progress
from dask_kubernetes import KubeCluster
from rasterio.session import AWSSession

cluster = KubeCluster(n_workers=1, env={"AWS_ACCESS_KEY_ID":"XXXX", "AWS_SECRET_ACCESS_KEY":"XXXXX"})
client = Client(cluster)

files = ["s3://my-bucket/test.tif"]

with rasterio.Env(AWSSession(aws_access_key_id="XXXX", aws_secret_access_key="XXXX")) as env:
    img = xr.open_rasterio(files[0], parse_coordinates=False, 
                              chunks={"band": 1, "x":5000, "y":5000})

    print(img)
    print(img.mean().compute())
```

I am not sure what is causing the issue, but the fact that it runs significantly faster on LocalCluster (which has the same resources as a single worker pod) than on a single worker pod leads me to believe that it is something related to the kubenetes worker pods.

**Comment by TomAugspurger** [comment]
What versions for s3fs and fsspec?

**Comment by system123** [comment]
fsspec -> 0.4.4
s3fs -> 0.3.4

I think it might be related to kube-dns looking internally first and then waiting for a timeout. How can this be disabled when starting KubeCluster from Python?

**Comment by jacobtomlinson** [comment]
You could be right about DNS or some other kubernetes networking issue. It could also be related to differences with temporary file storage. 

This is likely an issue with the kubernetes cluster you are using rather than this library. Therefore this issue may effect everything running on the cluster. 

Do you manage the cluster or has it been provided to you?

Also are your cluster and bucket in the same region?

**Comment by system123** [comment]
The worker pods use the following config
```
kind: Pod
metadata:
spec:
  nodeSelector:
    lifecycle: Ec2Spot
  restartPolicy: Never
  dnsPolicy: Default
  containers:
  - image: pangeo/pangeo-notebook:latest
    env:
    - name: AWS_ACCESS_KEY_ID
      value: "XXXX"
    - name: AWS_SECRET_ACCESS_KEY
      value: "XXXX"
    args:
      - dask-worker
      - --nthreads
      - '2'
      - --no-bokeh
      - --memory-limit
      - 6GB
      - --death-timeout
      - '60'
    name: dask-worker
    resources:
      limits:
        cpu: "1.75"
        memory: 6G
      requests:
        cpu: "1.75"
        memory: 6G
```
we are managing the cluster ourselves, it is implemented on AWS K8s, and everything is in the same region.
