### ISSUE TITLE
Workers timing out, unable to connect to the scheduler

### ISSUE THREAD

**Issue by Techn0logic** [dask/dask-kubernetes#176]
Hi, all.

I'm trying to use the KubeCluster but all worker pods seem to be unable to reach the scheduler

kubectl logs <dask-jovian-xxx> return this
```
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:39242'
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:45190
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:45190
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:35363
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          2
distributed.worker - INFO -                Memory:                    6.00 GB
distributed.worker - INFO -       Local Directory:           /worker-c_e9c_6d
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:35363
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:35363
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:35363
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:35363
distributed.worker - INFO - Waiting to connect to:      tcp://127.0.0.1:35363
distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:39242'
distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:45190
distributed.worker - INFO - Closed worker has not yet started: None
distributed.nanny - ERROR - Timed out connecting Nanny '<Nanny: None, threads: 2>' to scheduler 'tcp://127.0.0.1:35363'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/nanny.py", line 309, in instantiate
    timedelta(seconds=self.death_timeout), self.process.start()
tornado.util.TimeoutError: Timeout
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/opt/conda/bin/dask-worker", line 10, in <module>
    sys.exit(go())
  File "/opt/conda/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 406, in go
    main()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/distributed/cli/dask_worker.py", line 397, in main
    raise TimeoutError("Timed out starting worker.") from None
tornado.util.TimeoutError: Timed out starting worker.
```

kubernetes cluster runs in ec2

helm values for jupyter (`<host>` replaced with my ec2 host)
```
jupyter:
  name: jupyter
  enabled: true
  image:
    repository: "daskdev/dask-notebook"
    tag: 1.1.5
    pullPolicy: IfNotPresent
    pullSecrets:
    #  - name: regcred
  replicas: 1
  # serviceType: "ClusterIP"
  # serviceType: "NodePort"
  serviceType: "LoadBalancer"
  servicePort: 80
  ingress:
    enabled: true
    path: /
    # Used to create an Ingress record.
    hosts:
      - <host>
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/add-base-url: "true"
      # kubernetes.io/tls-acme: "true"
    labels: {}
    tls:
      #Secrets must be manually created in the namespace.
      - secretName: dask-scheduler-secret 
        hosts:
          - <host>

  # This hash corresponds to the password 'dask'
  password: 'sha1:aae8550c0a44:9507d45e087d5ee481a5ce9f4f16f37a0867318c'
  env:
   - name: EXTRA_CONDA_PACKAGES
     value: "jupyter-server-proxy dask-kubernetes -y -c conda-forge"
  tolerations: []
  nodeSelector: {}
  affinity: {}
```

role added to get/watch/list/create/delete pods
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "pods"]
  verbs: ["get", "watch", "create", "delete", "list"]
```

rolebinding

```
kubectl create clusterrolebinding service-reader-pod \
  --clusterrole=service-reader  \
  --serviceaccount=default:default
```

worker-spec.yaml
```
kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: daskdev/dask:latest
    imagePullPolicy: IfNotPresent
    args: [dask-worker, --nthreads, '2', --no-dasboard, --memory-limit, 6GB, --death-timeout, '60']
    name: dask
```

jobs seem to be submitted to the scheduler, but no workers available. Worker state is in Running - attempting to connect until  `--death-timeout` raises TimeoutError

some screenshots 
https://imgur.com/a/EuvN9em

anything obvious I'm missing?

Love Dask, thanks!

**Comment by jacobtomlinson** [comment]
Thanks for raising this! Sorry that you are having trouble with it. Could I ask you to share your current dask and distributed versions?

It seems concerning that the workers are listening on `127.0.0.1` and the trying to connect to the scheduler there too. This suggests that the pod IP addresses are not being correctly detected.

@mrocklin you mentioned yesterday that there was a breaking change upstream, could this be related?

**Comment by Techn0logic** [comment]
Thanks for getting back so quickly. 

sure
```
dask                      1.1.5                      py_0    conda-forge
dask-core                 1.1.5                      py_0    conda-forge
dask-kubernetes           0.9.2                      py_0    conda-forge
```

Yes, I found that surprising too. When I run helm deployment for `stable/dask` and connecting with `distributed.Client` - the client then displays pod hostnames, e.g `tcp://<pod-name>:port` instead of `localhost` in the adaptive case. In that case `client.compute` works as expected

But my aim is to use adaptive cluster

I run jupyterlab from  `daskdev/dask-notebook`

**Comment by jacobtomlinson** [comment]
Can you just run the following lines for me in your notebook?

```python
import socket
socket.gethostname()
```

**Comment by Techn0logic** [comment]
```
import socket
socket.gethostname()


'dask-jupyter-jupyter-84b6dd89c4-gmhrz'
```
returns the name of the pod on which I'm running jupyterlab

**Comment by jacobtomlinson** [comment]
Yeah, that is what I would expect, so it is strange that it is getting set to localhost somewhere.

Do you have anything in your `~/.config/dask` config files?

**Comment by Techn0logic** [comment]
```
client.get_versions()

{'scheduler': {'host': (('python', '3.7.3.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '4.4.0-1092-aws'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'en_US.UTF-8'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')),
  'packages': {'required': (('dask', '1.1.5'),
    ('distributed', '1.26.1'),
    ('msgpack', '0.6.1'),
    ('cloudpickle', '0.8.1'),
    ('tornado', '6.0.2'),
    ('toolz', '0.9.0')),
   'optional': (('numpy', '1.16.2'),
    ('pandas', '0.24.2'),
    ('bokeh', '1.0.4'),
    ('lz4', None),
    ('dask_ml', None),
    ('blosc', '1.8.1'))}},
 'workers': {},
 'client': {'host': [('python', '3.7.3.final.0'),
   ('python-bits', 64),
   ('OS', 'Linux'),
   ('OS-release', '4.4.0-1092-aws'),
   ('machine', 'x86_64'),
   ('processor', 'x86_64'),
   ('byteorder', 'little'),
   ('LC_ALL', 'en_US.UTF-8'),
   ('LANG', 'en_US.UTF-8'),
   ('LOCALE', 'en_US.UTF-8')],
  'packages': {'required': [('dask', '1.1.5'),
    ('distributed', '1.26.1'),
    ('msgpack', '0.6.1'),
    ('cloudpickle', '0.8.1'),
    ('tornado', '6.0.2'),
    ('toolz', '0.9.0')],
   'optional': [('numpy', '1.16.2'),
    ('pandas', '0.24.2'),
    ('bokeh', '1.0.4'),
    ('lz4', None),
    ('dask_ml', None),
    ('blosc', '1.8.1')]}}}
```

```
ls ~/.config/dask
distributed.yaml  kubernetes.yaml
```
contents in both files are all commented out

**Comment by Techn0logic** [comment]
what I tried
FYI - if that helps?

I ran `pip install dask_kubernetes==0.7.0`

This now returns IP addresses instead of `localhost`

![image](https://user-images.githubusercontent.com/8558101/65253902-53d6b980-daf3-11e9-9fd3-fc4657e506b1.png)
the IP refers to the endpoint for my jupyter service
```
NAME                   ENDPOINTS           AGE
dask-jupyter-jupyter         10.42.0.63:8888     24m
```

yet, workers are stuck with ```Waiting to connect to:     tcp://10.42.0.63:42397```

environment
```
environ{'LC_ALL': 'en_US.UTF-8',
        'DOCKER_REGISTRY_SERVICE_PORT': '5000',
        'DOCKER_REGISTRY_SERVICE_HOST': '10.43.223.8',
        'LANG': 'en_US.UTF-8',
        'HOSTNAME': 'dask-jupyter-jupyter-84b6dd89c4-kh7tw',
        'DASK_JUPYTER_JUPYTER_PORT_80_TCP_ADDR': '10.43.128.24',
        'EXTRA_CONDA_PACKAGES': 'jupyter-server-proxy dask-kubernetes -y -c conda-forge',
        'NB_UID': '1000',
        'DOCKER_REGISTRY_PORT_5000_TCP_ADDR': '10.43.223.8',
        'CONDA_DIR': '/opt/conda',
        'CONDA_VERSION': '4.6.7',
        'DASK_JUPYTER_JUPYTER_PORT_80_TCP_PROTO': 'tcp',
        'KUBERNETES_PORT_443_TCP_PROTO': 'tcp',
        'KUBERNETES_PORT_443_TCP_ADDR': '10.43.0.1',
        'DASK_JUPYTER_JUPYTER_SERVICE_PORT': '80',
        'DOCKER_REGISTRY_PORT_5000_TCP': 'tcp://10.43.223.8:5000',
        'KUBERNETES_PORT': 'tcp://10.43.0.1:443',
        'PWD': '/home/jovyan',
        'HOME': '/home/jovyan',
        'DASK_SCHEDULER_ADDRESS': 'dask-jupyter-scheduler:8786',
        'DOCKER_REGISTRY_SERVICE_PORT_REGISTRY': '5000',
        'DOCKER_REGISTRY_PORT': 'tcp://10.43.223.8:5000',
        'KUBERNETES_SERVICE_PORT_HTTPS': '443',
        'DEBIAN_FRONTEND': 'noninteractive',
        'KUBERNETES_PORT_443_TCP_PORT': '443',
        'DASK_JUPYTER_JUPYTER_PORT': 'tcp://10.43.128.24:80',
        'DASK_JUPYTER_JUPYTER_PORT_80_TCP': 'tcp://10.43.128.24:80',
        'NB_USER': 'jovyan',
        'DASK_JUPYTER_JUPYTER_SERVICE_PORT_DASK_JUPYTER_JUPYTER': '80',
        'KUBERNETES_PORT_443_TCP': 'tcp://10.43.0.1:443',
        'SHELL': '/bin/bash',
        'DASK_JUPYTER_JUPYTER_SERVICE_HOST': '10.43.128.24',
        'DASK_JUPYTER_JUPYTER_PORT_80_TCP_PORT': '80',
        'SHLVL': '1',
        'LANGUAGE': 'en_US.UTF-8',
        'KUBERNETES_SERVICE_PORT': '443',
        'DOCKER_REGISTRY_PORT_5000_TCP_PORT': '5000',
        'DOCKER_REGISTRY_PORT_5000_TCP_PROTO': 'tcp',
        'NB_GID': '100',
        'PATH': '/opt/conda/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        'KUBERNETES_SERVICE_HOST': '10.43.0.1',
        'MINICONDA_VERSION': '4.5.12',
        'JPY_PARENT_PID': '193',
        'TERM': 'xterm-color',
        'CLICOLOR': '1',
        'PAGER': 'cat',
        'GIT_PAGER': 'cat',
        'MPLBACKEND': 'module://ipykernel.pylab.backend_inline'}```

**Comment by mrocklin** [comment]
(Jacob, the break upstream was only for adaptive)

**Comment by Techn0logic** [comment]
I was able to connect workers by using older versions

on jupyter
```
pip list | grep "dask\|distributed"

dask                2.3.0
dask-kubernetes    0.7.0    
distributed        1.28.1   

```

on workers
```
pip list | grep "dask\|distributed"
dask                   2.3.0    
distributed            1.28.1 
```

![image](https://user-images.githubusercontent.com/8558101/65264709-1e3bcb80-db07-11e9-90a1-383034ade15f.png)

I can run compute and get results in this configuration.

**Comment by Techn0logic** [comment]
any pointers why it wouldn't work with `dask-kubernetes==9.x.x` and `distributed==2.x.x` when using latest `daskdev/dask-notebook` image? what would be the action on this one?

**Comment by jacobtomlinson** [comment]
Are you still facing these issues on the master branch?

**Comment by Techn0logic** [comment]
Tried `0.10.0` and still unable to bring up workers

This is running `helm install stable/dask` with `dask_kubernetes`


I don't get timeouts this time, but when I increase number of workers via the widget ui or `cluster.scale()` worker pods don't come up and nothing at all happens. `kubectl get pods -A` doesn't show any pods being created


```! pip list | grep dask

dask                 2.6.0   
dask-kubernetes      0.10.0  

! pip list | grep distributed

distributed          2.6.0   
```

Nothing hard-coded in dask/kubernetes config files

`dask.config.config`
```
{ 'scheduler_address': 'daskdev-scheduler:8786',
 'temporary-directory': None,
 'array': {'svg': {'size': 120}},
 'kubernetes': {'name': 'dask-{user}-{uuid}',
  'namespace': None,
  'count': {'start': 0, 'max': None},
  'host': '0.0.0.0',
  'port': 0,
  'env': {},
  'scheduler-timeout': '5 minutes',
  'deploy-mode': 'local',
  'interface': None,
  'protocol': 'tcp://',
  'dashboard_address': ':8787',
  'scheduler-service-type': 'ClusterIP',
  'scheduler-service-template': {'apiVersion': 'v1',
   'kind': 'Service',
   'spec': {'selector': {'dask.org/cluster-name': '',
     'dask.org/component': 'scheduler'},
    'ports': [{'name': 'comm',
      'protocol': 'TCP',
      'port': 8786,
      'targetPort': 8786},
     {'name': 'dashboard',
      'protocol': 'TCP',
      'port': 8787,
      'targetPort': 8787}]}},
  'worker-template-path': None,
  'worker-template': {}},
 'distributed': {'version': 2,
  'scheduler': {'allowed-failures': 3,
   'bandwidth': 100000000,
   'blocked-handlers': [],
   'default-data-size': 1000,
   'events-cleanup-delay': '1h',
   'idle-timeout': None,
   'transition-log-length': 100000,
   'work-stealing': True,
   'worker-ttl': None,
   'pickle': True,
   'preload': [],
   'preload-argv': [],
   'default-task-durations': {},
   'dashboard': {'status': {'task-stream-length': 1000},
    'tasks': {'task-stream-length': 100000},
    'tls': {'ca-file': None, 'key': None, 'cert': None}}},
  'worker': {'blocked-handlers': [],
   'multiprocessing-method': 'forkserver',
   'use-file-locking': True,
   'connections': {'outgoing': 50, 'incoming': 10},
   'preload': [],
   'preload-argv': [],
   'daemon': True,
   'lifetime': {'duration': None, 'stagger': '0 seconds', 'restart': False},
   'profile': {'interval': '10ms', 'cycle': '1000ms', 'low-level': False},
   'memory': {'target': 0.6, 'spill': 0.7, 'pause': 0.8, 'terminate': 0.95}},
  'client': {'heartbeat': '5s'},
  'deploy': {'lost-worker-timeout': '15s'},
  'comm': {'compression': 'auto',
   'default-scheme': 'tcp',
   'socket-backlog': 2048,
   'recent-messages-log-length': 0,
   'zstd': {'level': 3, 'threads': 0},
   'timeouts': {'connect': '10s', 'tcp': '30s'},
   'require-encryption': False,
   'tls': {'ciphers': None,
    'ca-file': None,
    'scheduler': {'cert': None, 'key': None},
    'worker': {'key': None, 'cert': None},
    'client': {'key': None, 'cert': None}}},
  'dashboard': {'link': '{scheme}://{host}:{port}/status',
   'export-tool': False},
  'admin': {'tick': {'interval': '20ms', 'limit': '3s'},
   'max-error-length': 10000,
   'log-length': 10000,
   'log-format': '%(name)s - %(levelname)s - %(message)s',
   'pdb-on-err': False}}}
```




With "deploy_mode='remote'" I get error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-8d9be1b2f2e4> in <module>
      1 from dask_kubernetes import KubeCluster
----> 2 c = KubeCluster.from_yaml("worker-spec.yaml", deploy_mode="remote")
      3 c.scale(10)
      4 c

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in from_yaml(cls, yaml_path, **kwargs)
    564             d = yaml.safe_load(f)
    565             d = dask.config.expand_environment_variables(d)
--> 566             return cls.from_dict(d, **kwargs)
    567 
    568     @property

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in from_dict(cls, pod_spec, **kwargs)
    526         KubeCluster.from_yaml
    527         """
--> 528         return cls(make_pod_from_dict(pod_spec), **kwargs)
    529 
    530     @classmethod

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in __init__(self, pod_template, name, namespace, n_workers, host, port, env, auth, scheduler_timeout, deploy_mode, interface, protocol, dashboard_address, security, **kwargs)
    378         self.auth = auth
    379         self.kwargs = kwargs
--> 380         super().__init__(**self.kwargs)
    381 
    382     async def _start(self):

/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py in __init__(self, workers, scheduler, worker, asynchronous, loop, security, silence_logs, name)
    240         if not self.asynchronous:
    241             self._loop_runner.start()
--> 242             self.sync(self._start)
    243             self.sync(self._correct_state)
    244 

/opt/conda/lib/python3.7/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    160             return future
    161         else:
--> 162             return sync(self.loop, func, *args, **kwargs)
    163 
    164     async def _logs(self, scheduler=True, workers=True):

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    331     if error[0]:
    332         typ, exc, tb = error[0]
--> 333         raise exc.with_traceback(tb)
    334     else:
    335         return result[0]

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in f()
    315             if callback_timeout is not None:
    316                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 317             result[0] = yield future
    318         except Exception as exc:
    319             error[0] = sys.exc_info()

/opt/conda/lib/python3.7/site-packages/tornado/gen.py in run(self)
    727 
    728                     try:
--> 729                         value = future.result()
    730                     except Exception:
    731                         exc_info = sys.exc_info()

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in _start(self)
    498         self.worker_spec = {i: self.new_spec for i in range(self._n_workers)}
    499 
--> 500         await super()._start()
    501 
    502     @classmethod

/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py in _start(self)
    266 
    267         self.status = "starting"
--> 268         self.scheduler = await self.scheduler
    269         self.scheduler_comm = rpc(
    270             getattr(self.scheduler, "external_address", None) or self.scheduler.address,

/opt/conda/lib/python3.7/site-packages/distributed/deploy/spec.py in _()
     39             async with self.lock:
     40                 if self.status == "created":
---> 41                     await self.start()
     42                     assert self.status == "running"
     43             return self

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in start(self, **kwargs)
    149         await super().start(**kwargs)
    150 
--> 151         while (await self.describe_pod()).status.phase == "Pending":
    152             await asyncio.sleep(0.1)
    153 

/opt/conda/lib/python3.7/site-packages/dask_kubernetes/core.py in describe_pod(self)
     95     async def describe_pod(self):
     96         self._pod = await self.core_api.read_namespaced_pod(
---> 97             self._pod.metadata.name, self.namespace
     98         )
     99         return self._pod

AttributeError: 'NoneType' object has no attribute 'metadata'

```

**Comment by jacobtomlinson** [comment]
> This is running helm install stable/dask with dask_kubernetes

That help chart isn't really related to `dask-kubernetes` other than using the same technologies to deploy a similar cluster.

Do you have correct permissions for creating pods as per the [documentation](https://github.com/dask/dask-kubernetes/blob/master/doc/source/index.rst#role-based-access-control-rbac)?

**Comment by Techn0logic** [comment]
Correct, lacked permissions

Needed to create 

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskKubernetes
rules:
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods/log"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "" # indicates the core API group
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"
```

and bind it

```
 kubectl create clusterrolebinding dask-pod-creator \      
  --clusterrole=daskKubernetes  \
  --serviceaccount=default:default
```

Now works like a charm. Thank you so much for your help!
