### ISSUE TITLE
Document RBAC requirements

### ISSUE THREAD

**Issue by athornton** [dask/dask-kubernetes#181]
I think this happened in vanilla 0.9.2 (although I saw it today while trying to test PR #162 )

What are the items I need for my RBAC role now?  (This worked through 0.9.1)

```
ApiException: (403)
Reason: Forbidden
HTTP response headers: <CIMultiDictProxy('Audit-Id': 'cc9a1ae7-1483-4d97-89b8-d3f7cab86171', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 01 Oct 2019 18:43:50 GMT', 'Content-Length': '373')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"dask-athornton-3691b3ef-c4mq9q\" is forbidden: User \"system:serviceaccount:nublado-athornton:dask\" cannot get resource \"pods\" in API group \"\" in the namespace \"nublado-athornton\"","reason":"Forbidden","details":{"name":"dask-athornton-3691b3ef-c4mq9q","kind":"pods"},"code":403}
```

I don't understand what I need that I don't have, since it looks like it should be "list pods", because here's my RBAC Role:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: 2019-03-20T18:37:53Z
  name: dask
  namespace: nublado
  resourceVersion: "955"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/nublado/roles/dask
  uid: 4586ccf1-4b3f-11e9-9204-42010a800055
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - create
  - delete
```

**Comment by Techn0logic** [comment]
I'm running into issues as well, and looking through how to define these properly just now

Binding it to service-reader works for me
```kubectl create clusterrolebinding service-reader-pod \
  --clusterrole=service-reader  \
  --serviceaccount=default:default
```
but binding to a custom service-account doesn't

Trying to figure out why

**Comment by jacobtomlinson** [comment]
Are you still facing these issues? 

A quick look again at your issue shows the error states you do not have permissions in `nublado-athornton` and your RBAC config os giving you permission to `nublado`. Which makes sense why you are getting the error.

Could you try granting permissions to `nublado-athornton` and trying again?

**Comment by athornton** [comment]
Turns out pods need "get" and "watch" as well, and "pods/log" need all five too.

With those changes it's working.  I'll close this.

**Comment by jacobtomlinson** [comment]
Ah thanks for checking that. We really should cover this in the documentation. I'm going to re-open this until we have correctly documented things.

To create workers you need the following permissions

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskKubernetes
rules:
- apiGroups: 
  - ""  # indicates the core API group
  resources: 
  - "pods"
  verbs: 
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"
- apiGroups: 
  - ""  # indicates the core API group
  resources: 
  - "pods/log"
  verbs: 
  - "get"
  - "list"
```

For the new remote scheduler functionality you also need

```yaml
- apiGroups: 
  - "" # indicates the core API group
  resources: 
  - "services"
  verbs: 
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"
```

We should add this to the documentation. @athornton do you have any interest in contributing this?
