### ISSUE TITLE
Worker image from private docker repo

### ISSUE THREAD

**Issue by Techn0logic** [dask/dask-kubernetes#182]
Is there a  way to provide `imagePullSecrets`to pull from a private repo? - as it is desired to build custom worker images, environment,  and pull them from a private repo to avoid serialisation problems between scheduler - workers. 

e.g `worker-spec.yaml`
```
kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: <privateRepo>:<customImage>:latest
    imagePullPolicy: IfNotPresent
    pullSecrets:
      - name: regcred
    args: [dask-worker, $(DASK_SCHEDULER_ADDRESS),--nthreads, '2', --memory-limit, 2GB]
    name: dask-worker
```

pullSecrets not passed into the pod 

```
dask                      2.3.0                      py_0    conda-forge
dask-core                 2.3.0                      py_0    conda-forge
dask-kubernetes           0.7.0                    pypi_0    pypi
dask-labextension         1.0.3                      py_0    conda-forge
distributed               1.28.1                   pypi_0    pypi
```

**Comment by jacobtomlinson** [comment]
Thanks for raising this!

Looking at the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret) I'm not sure you have your pod config quite right.

Could you try this?

```yaml
kind: Pod
metadata:
  labels:
    foo: bar
spec:
  restartPolicy: Never
  containers:
  - image: <privateRepo>:<customImage>:latest
    imagePullPolicy: IfNotPresent
    args: [dask-worker, $(DASK_SCHEDULER_ADDRESS),--nthreads, '2', --memory-limit, 2GB]
    name: dask-worker
  imagePullSecrets:
  - name: regcred
```
