### ISSUE TITLE
KubeCluster fails to adapt 

### ISSUE THREAD

**Issue by heavenmarshal** [dask/dask-kubernetes#244]
I found the KubeCluster fails to adapt. After I call
```python
>>> cluster.adapt(minimum=2, maximum=2)
```
it is supposed to create a new worker pod if I delete one worker pod by kubectl delete pods (actually it is the behavior of the previous version, e.g. 0.8.0). However, there is no new worker created if I use the latest version 0.10.1. My code and configuration is provided blow.
```Dockerfile
# Dockerfile
FROM python
WORKDIR /app
RUN pip install dask==2.14.0 \
	&& pip install distributed==2.14.0 \
	&& pip install dask-kubernetes==0.10.1
COPY k8s_cluster.py /app
COPY worker/worker.yaml /app
```
```python
# k8s_cluster.py
import os
import yaml
from dask_kubernetes import KubeCluster

def build_k8s_cluster(n_workers):
    worker_config = yaml.safe_load(open('worker.yaml', 'r'))
    pod_name = worker_config['metadata'].pop('name', 'dask-worker') + '-{uuid}'
    namespace = os.getenv('MY_POD_NAMESPACE')
    cluster = KubeCluster.from_dict(worker_config, namespace=namespace, name=pod_name)
    cluster.adapt(minimum=n_workers, maximum=n_workers)
    return cluster
```
```yaml
# pod.yaml, manifest for the scheduler pod
apiVersion: v1
kind: Pod
metadata:
  name: example
  namespace: example
spec:
  serviceAccountName: example-serviceaccount
  restartPolicy: Never
  containers:
  - name: example
    image: heavenmarshal/dask-k8s-adapt
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["2000"]
    env:
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
```
```yaml
# worker/worker.yaml manifest file for the workers
kind: Pod
metadata:
  name: dask-worker
spec:
  restartPolicy: Never
  containers:
    - image: "heavenmarshal/dask-k8s-adapt"
      imagePullPolicy: Always
      command: ["/bin/bash"]
      args: ["-c", "dask-worker --nthreads '1' --no-bokeh --memory-limit 200Mi --death-timeout '60'"]
      name: dask-worker
      env:
        - name: EXTRA_PIP_PACKAGES
          value: fastparquet git+https://github.com/dask/distributed
        - name: PYTHONPATH
          value: /app
      resources:
        limits:
          cpu: "1"
          memory: "200Mi"
        requests:
          cpu: "0.5"
          memory: "50Mi"
```
The manifest files for role, rolebinding and serviceaccount are omitted.
