### ISSUE TITLE
deployed pod doesnt have controlled by in kubectl describe

### ISSUE THREAD

**Issue by sivaguru-pat** [dask/dask-kubernetes#332]
tried deploying 2 node cluster with example given in the documentation . the scheduler and the workers are up without controlled by parameter. attached the yaml file below

```yaml
kind: Pod
metadata:
  labels:
    app: gpu-worker
namespace: argo-deployment
spec:

  restartPolicy: Never
  containers:
  - image: rapidsai/rapidsai-core:0.18-cuda10.2-runtime-ubuntu16.04-py3.8
    imagePullPolicy: IfNotPresent
    args: [dask-cuda-worker, $(DASK_SCHEDULER_ADDRESS), --rmm-pool-size, 4GB]
    name: dask-cuda
    resources:
      limits:
        cpu: "2"
        memory: 6G
        nvidia.com/gpu: 1 # requesting 1 GPU
      requests:
        cpu: "2"
        memory: 6G
        nvidia.com/gpu: 1 # requesting 1 GPU
```
