### ISSUE TITLE
Additional worker group quirks

### ISSUE THREAD

**Issue by ljstrnadiii** [dask/dask-kubernetes#408]
There are two side affects of my first use of additional worker groups. The files used for deployment are defined below. 

## 1. Jupyter values seem to get overwritten:
If jupyter is disabled in `values.yaml` and I create an `additional_groups.yaml` to upgrade as described in the [blog post](https://github.com/dask/dask-blog/blob/gh-pages/_posts/2022-02-17-helm-multiple-worker-groups.md), then jupyter will get deployed during the upgrade. Reproducing:
1. `helm install dask dask/dask -f values.yaml` (notice that jupyter is disabled; `kubectl get pods` shows no jupyter)
2. `helm upgrade -f additional_workers.yaml dask dask/dask` (`kubectl get pods` shows a newly deployed jupyter)

## 2. Replica count gets overwritten if zero:
If I specify `replica=0` for additional worker groups, the replica value from values.yaml is used (`kubectl get pods` shows 3 pods). If I set replica to 1 in `additional_workers.yaml`, then it sets to 1. I was expecting to be able to set replica to 0. Thi swould help to facilitate many worker types and be able to stand them up in code when needed without having to have any machines idling. Interestingly, setting replica to 0 in values.yaml for the main deployment will result in 0 workers (only the scheduler will stand up). Reproducing:
1. `helm install dask dask/dask -f values.yaml` (notice 3 replicas for main workers in values.yaml)
2. `helm upgrade -f additional_workers.yaml dask dask/dask` (notice 0 replicas defined, but `kubectl get pods` shows 3 workers for additional group.)

```
# values.yaml
scheduler:
  ...
webUI:
 ...

worker:
  ...
  replicas: 3  # Number of workers.
  
jupyter:
  name: jupyter  # Jupyter name.
  enabled: false  # Enable/disable the bundled Jupyter notebook.
```
and
```
# additional_worker_groups.yaml
additional_worker_groups: # Additional groups of workers to create
  - name: gpu-workers # Dask worker group name.
    replicas: 0
    image:
      repository: rapidsai/rapidsai-core
      tag: 21.12-cuda11.0-runtime-ubuntu20.04-py3.8
      dask_worker: dask-cuda-worker
    extraArgs:
      - --resources
      - "GPU=1"
    resources:
      limits:
        nvidia.com/gpu: 1
```

I figured these two issues might be related so decided to post in one issue. Thanks for all the work @Matt711 and @jacobtomlinson ! Super super cool stuff.
