### ISSUE TITLE
Custom affinity is overridden by default affinity

### ISSUE THREAD

**Issue by csymeonides-mf** [dask/dask-kubernetes#506]
**What happened**:

I am trying to set a custom affinity on my Dask worker pods. I realise there is a [default affinity](https://github.com/dask/dask-kubernetes/issues/146) already defined, but I would prefer to use my own.

My custom affinity is something like this:
```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: foo
              operator: In
              values:
                - bar
```

However when the pod starts up, it only contains the default affinity (output from `kubectl get pod -o yaml`:
```
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: k8s.dask.org/node-purpose
            operator: In
            values:
            - worker
        weight: 100
```

**What you expected to happen**:

I expected the affinity I specified to be used in the pod spec.

Looking at the [merged PR](https://github.com/dask/dask-kubernetes/pull/147) for this issue, the behaviour is driven by an argument `match_node_purpose` to the function `clean_pod_template()`. However, there is no code that sets `match_node_purpose` to any value other than the default of `"prefer"`.

**Suggestion**:

Allow `KubeCluster` to accept a new argument and use it to set the `match_node_purpose` value in the call to `clean_pot_template()`. 

I might further suggest modifying the arg name and values to make it a bit clearer, e.g. `apply_default_affinity` which could be `preferred`, `required` or `none` (there might be an even clearer approach here but can't think of one right now).
