### ISSUE TITLE
dask operator scheduler service name

### ISSUE THREAD

**Issue by webcoderz** [dask/dask-kubernetes#561]
is it possible to change the service name having issues trying to connect my workers and other containers to the scheduler using dask-scheduler:8786 ? the dask-scheduler:8786 value is hardcoded in another image container so trying to avoid changing that elsewhere

**Comment by webcoderz** [comment]
```
    service:
      metadata:
        name: dask-scheduler
      type: ClusterIP
      selector:
        dask.org/cluster-name: dask
        dask.org/component: scheduler
      ports:
      - name: tcp-comm
        protocol: TCP
        port: 8786
        targetPort: "tcp-comm"
      - name: http-dashboard
        protocol: TCP
        port: 8787
        targetPort: "http-dashboard"

```
just in case people look here in future
