### ISSUE TITLE
Kubernetes deployment of many workers on many-cpu machines is very slow

### ISSUE THREAD

**Issue by ckemere** [dask/dask-kubernetes#57]
I was trying to do some comparisons between joblib and joblib-with-distributed-backend and so tried to provision 2 or 3 96 or 64 cpu machines with 40-60 workers and 40-60 cpus for the notebook worker on google cloud. I found that the provisioning process would take quite long. I think this may just reflect underlying slowness in the container process, but if you guys have any insight that would be great.

**Comment by martindurant** [comment]
How slow is "quite long"?
It will probably depend on which region you request, and the node type - you may get faster response with a larger number of smaller machines.

**Comment by ckemere** [comment]
a few 10s of minutes (and it crashed a couple of times). I found that 6 n1-standard-8 machines took about 1 minutes in the same us-central1-a region...

**Comment by halfdanrump** [comment]
@ckemere Could it be that there are simply not that many 64 or 96 CPU machines available in that region?

**Comment by martindurant** [comment]
@halfdanrump : one guess would be the time to download the docker images; I suppose dockerhub only has the one location in the US.

**Comment by ckemere** [comment]
@halfdanrump - I'm not having any problems getting them via the compute (rather than cluster) route?

@martindurant - I don't think it's download time b/c I don't have issues if I ask for many _nodes_. Unless it tries to download it many times to the same node? I was imagining that there must be some  sort of contention between different docker processes when they're starting.

Here's the yaml file I was using:
```
cluster:
  num_nodes: 2 # 3
  machine_type: n1-standard-64 # n1-standard-8
  disk_size: 50
  zone: us-central1-a
  autoscaling: False
  min_nodes: 1
  max_nodes: 32
jupyter:
  memory: 64000Mi # 4096Mi
  cpus: 32 # 1
  port: 8888
  lab_port: 8889
  image: ckemere/dask-kubernetes:latest
scheduler:
  memory: 4096Mi
  cpus: 1
  image: ckemere/dask-kubernetes:latest
  tcp_port: 8786
  http_port: 9786
  bokeh_port: 8787
workers:
  count: 40 # 8
  cpus_per_worker: 1.8
  memory_per_worker: 6800Mi
  mem_factor: 0.95
  image: ckemere/dask-kubernetes:latest
```
