### ISSUE TITLE
Worker group doesn't recover after pod deletion

### ISSUE THREAD

**Issue by kwohlfahrt** [dask/dask-kubernetes#603]
**Describe the issue**:

When creating a Dask cluster, it initially starts with the correct number of worker pods. If a pod is deleted (e.g. due to a spot node terminating), this pod is never restored by the operator.

This makes dask largely unusable with spot-instance based clusters, as these may be terminated at any time, and Dask makes no attempt to restore them, leading to stuck jobs that still have some tasks remaining.

**Minimal Complete Verifiable Example**:

Create a DaskCluster with some number of replicas configured. I include the full spec below, but there's nothing special about it. Observe the expected pods are created:

```
> kubectl get pods -owide
NAME                                 READY   STATUS    RESTARTS   AGE   IP              NODE                  NOMINATED NODE   READINESS GATES
kai-dask-default-worker-c0bb7c3c84   1/1     Running   0          70s   172.17.3.212    i-0df7352caf719062b   <none>           <none>
kai-dask-default-worker-e0bf26f836   1/1     Running   0          70s   172.17.47.193   i-02d06289e1302494d   <none>           <none>
kai-dask-default-worker-f8c5481c0e   1/1     Running   0          70s   172.17.40.35    i-042e23bf8d47eae8d   <none>           <none>
kai-dask-scheduler                   1/1     Running   0          71s   172.17.17.137   i-0903e12b5218ba300   <none>           <none>
```

Then, terminate a node hosting one of the workers. In my case, I terminated node `i-0df7352caf719062b`. Wait for the node to shutdown & be removed from the cluster. Observe that the cluster now only has two workers left:

```
> kubectl get pods -owide
NAME                                 READY   STATUS    RESTARTS   AGE     IP              NODE                  NOMINATED NODE   READINESS GATES
kai-dask-default-worker-e0bf26f836   1/1     Running   0          6m42s   172.17.47.193   i-02d06289e1302494d   <none>           <none>
kai-dask-default-worker-f8c5481c0e   1/1     Running   0          6m42s   172.17.40.35    i-042e23bf8d47eae8d   <none>           <none>
kai-dask-scheduler                   1/1     Running   0          6m43s   172.17.17.137   i-0903e12b5218ba300   <none>           <none>
```

The third node is never restored. This can be tested much more quickly by deleting the pod instead of the whole node.

**Anything else we need to know?**:

It appears there is a test for this case in the [classic controller](https://github.com/dask/dask-kubernetes/blob/3fe8e28479825d05bb3f8dcd9ff1c7f5a5c4795a/dask_kubernetes/classic/tests/test_async.py#L785), but not in the new operator.

**Environment**:

- Dask version: `2022.10.0`
- Operator version: `2022.10.1`

`dask.yaml`:

```yaml
apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: kai-dask
spec:
  scheduler:
    service:
      ports:
      - name: tcp-comm
        port: 8786
        protocol: TCP
        targetPort: tcp-comm
      - name: http-dashboard
        port: 8787
        protocol: TCP
        targetPort: http-dashboard
      selector:
        dask.org/cluster-name: kai-dask
        dask.org/component: scheduler
      type: ClusterIP
    spec:
      containers:
      - command:
        - dask
        - scheduler
        image: ghcr.io/dask/dask:2022.10.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 15
          periodSeconds: 20
        name: scheduler
        ports:
        - containerPort: 8786
          name: tcp-comm
          protocol: TCP
        - containerPort: 8787
          name: http-dashboard
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: http-dashboard
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
  worker:
    replicas: 3
    spec:
      containers:
      - args:
        - --name
        - $(DASK_WORKER_NAME)
        command:
        - dask
        - worker
        image: ghcr.io/dask/dask:2022.10.0
        imagePullPolicy: Always
        name: worker
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
```
