### ISSUE TITLE
k8s operator: autoscaling hitting permissions issue

### ISSUE THREAD

**Issue by jmif** [dask/dask-kubernetes#637]
**Describe the issue**:

I've installed the latest k8s operator via helm on to a GKE cluster (v1.25.3-gke.800):

```
helm install --create-namespace -n dask-operator --generate-name dask/dask-kubernetes-operator 

 helm list -n dask-operator
NAME                                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
dask-kubernetes-operator-1672099696     dask-operator   1               2022-12-26 19:08:19.812767 -0500 EST    deployed        dask-kubernetes-operator-2022.12.0      2022.4.1   
```

I've made no modifications to the default configuration / permissions structure of the dask cluster nor the GKE cluster.   I'm able to create a `DaskCluster` (and `DaskJob`s) with no problem, but attaching a `DaskAutoscaler` to the cluster causes permissions errors in the operator that prevents autoscaling from working

```
Timer 'daskautoscaler_adapt' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 279, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/execution.py", line 374, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.8/site-packages/kopf/_core/actions/invocation.py", line 116, in invoke
    result..., 'X-Kubernetes-Pf-Prioritylevel-Uid': 'xxx', 'Date': 'Tue, 27 Dec 2022 05:28:34 GMT', 'Content-Length': '311')>
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"nodes is forbidden: User \"system:serviceaccount:dask-operator:dask-kubernetes-operator-1672099696\" cannot list resource \"nodes\" in API group \"\" at the cluster scope","reason":"Forbidden","details":{"kind":"nodes"},"code":403}
``` 

**Minimal Complete Verifiable Example**:

I'm able to reproduce the issue with the configuration in the [docs](https://kubernetes.dask.org/en/latest/operator_resources.html):

```
apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  name: simple
spec:
  worker:
    replicas: 2
    spec:
      containers:
      - name: worker
        image: "ghcr.io/dask/dask:latest"
        imagePullPolicy: "IfNotPresent"
        args:
          - dask-worker
          - --name
          - $(DASK_WORKER_NAME)
  scheduler:
    spec:
      containers:
      - name: scheduler
        image: "ghcr.io/dask/dask:latest"
        imagePullPolicy: "IfNotPresent"
        args:
          - dask-scheduler
        ports:
          - name: tcp-comm
            containerPort: 8786
            protocol: TCP
          - name: http-dashboard
            containerPort: 8787
            protocol: TCP
        readinessProbe:
          httpGet:
            port: http-dashboard
            path: /health
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: http-dashboard
            path: /health
          initialDelaySeconds: 15
          periodSeconds: 20
    service:
      type: NodePort
      selector:
        dask.org/cluster-name: simple
        dask.org/component: scheduler
      ports:
      - name: tcp-comm
        protocol: TCP
        port: 8786
        targetPort: "tcp-comm"
      - name: http-dashboard
        protocol: TCP
        port: 8787
        targetPort: "http-dashboard"
---
apiVersion: kubernetes.dask.org/v1
kind: DaskAutoscaler
metadata:
  name: simple
spec:
  cluster: "simple"
  minimum: 1  # we recommend always having a minimum of 1 worker so that an idle cluster can start working on tasks immediately
  maximum: 10 # you can place a hard limit on the number of workers regardless of what the scheduler requests
```
