### ISSUE TITLE
Support kubectl auth plugins for Python API

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#678]
Raising this issue based on https://dask.discourse.group/t/deploying-dask-with-aks/1649.

Some Kubernetes platforms use plugins to handle authentication. The example from the discussion is [AKS/AAD](https://learn.microsoft.com/en-us/azure/aks/managed-aad). The user cannot create clusters with `KubeCluster` and gets a `401 Unauthorized` error. But if they create a `DaskCluster` resource with `kubectl` it works fine.

My guess is that `kubernetes-asyncio`/`pykube-ng` don't support the `exec` mode of authentication that `kubectl` has.

```yaml
# Excerpt from kubeconfig generated with 'az aks get-credentials' with an AAD/AKS cluster
users:
- name: clusterUser_resourceGroup_aksClusterName
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <server id>
      - --client-id
      - <client id>
      - --tenant-id
      - <tenant id>
      - --login
      - devicecode
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
