### ISSUE TITLE
Add optional ServiceMonitor

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#687]
On the Dask Forum user `preneond` asked if the operator has the ability to include a `ServiceMonitor` resource as the [helm chart does](https://github.com/dask/helm-chart/blob/40e7b688d474969af2e1ee14f2fedeb4afa2d0cb/dask/values.yaml#L37-L51). Right now the answer is no.

https://dask.discourse.group/t/deploying-dask-kubernetes-operator-with-enabled-service-monitor/1692

It would be nice to add this.

**Comment by preneond** [comment]
@jacobtomlinson Wow., thank you! I already forked the repo and wanted to create PR for that feature. It would be also nice to have specs customizable in `make_scheduler_spec`  / `make_worker_spec`  to include some extra matadata labels when creating KubeCluster instance.

**Comment by jacobtomlinson** [comment]
Right now we propagate labels from the top-level `DaskCluster` and `DaskWorkerGroup` objects down to their child resources. So if you set `foo=bar` on the `DaskCluster` then you could use the `foo=bar,dask.org/component=scheduler` selector to select the scheduler service.

**Comment by jacobtomlinson** [comment]
Ok now that #688 is merged we can also create a `PodMonitor` to scrape worker metrics.

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dask-operator-workers
  labels:
    dask.org/component: "worker"
spec:
  selector:
    matchLabels:
      dask.org/component: "worker"
  podTargetLabels:
    - dask.org/cluster-name
    - dask.org/workergroup-name
  podMetricsEndpoints:
  - interval: 15s
    port: http-dashboard
```
