### ISSUE TITLE
Support auth without refresh tokens

### ISSUE THREAD

**Issue by droctothorpe** [dask/dask-kubernetes#775]
Not all cluster auth providers support refresh tokens. `KubeCluster` fails to instantiate without one out of cluster when parsing the Kubernetes configuration file. It would be helpful if there was a `refresh_token` flag or something to that effect in either `KubeCluster` or one of the auth plugins it accepts. Happy to contribute.

**Comment by droctothorpe** [comment]
Here's what the `user` section of my `~/.kube/config` file looks like:

```yaml
users:
- name: <obfuscated>
  user:
    auth-provider:
      config:
        client-id: <obfuscated>
        client-secret: <obfuscated>
        extra-scopes: <obfuscated>
        id-token: <obfuscated>
        idp-issuer-url: <obfuscated>
      name: <obfuscated>
  ```
  
In particular, please note the absence of a `refresh-token` field. `operator.KubeClient` assumes that field is there, and raises an exception when it doesn't find it. Not all cluster admins enable refresh tokens (case in point). It would be helpful if `KubeClient` worked without one.
