### ISSUE TITLE
Configruable scaling cool down period

### ISSUE THREAD

**Issue by BitTheByte** [dask/dask-kubernetes#819]
Implement a way to set a cool-down period for adaptive scaling instead of the hardcoded https://github.com/dask/dask-kubernetes/blob/92714da5785709726f85c4c6ec92451f5c23ad04/dask_kubernetes/operator/controller/controller.py#L816 e.g.

```yaml
apiVersion: kubernetes.dask.org/v1
kind: DaskCluster
metadata:
  annotations:
    kubernetes.dask.org/cooldown-until-interval: "30s"
  name: dask-f3a0c12f
  namespace: default
spec:
  ....
```
