### ISSUE TITLE
Using environment variables to update values in worker-spec.yml

### ISSUE THREAD

**Issue by jhamman** [dask/dask-kubernetes#92]
In the dask configuration module, it is possible to use environment variables to update configuration values. It doesn't seem that is currently possible here as the "worker-spec.yml" file is actually a kubernetes spec, rather than a dask config file. I'm curious if there is a way to do that now or if it would be feasible to add such functionality. 

somewhat related to #88, #45

Background for my particular use case: https://github.com/jupyterhub/kubespawner/pull/193, https://github.com/jupyter/repo2docker/pull/363

**Comment by mrocklin** [comment]
dask-kubernetes provides two ways to specify the worker template, either as a separate standalone file with a reference to that file in the config, or by placing the entire worker template into the config file.  Here is our current blank config file

```yaml
kubernetes:
  name: "dask-{user}-{uuid}"
  namespace: null
  count:
    start: 0
    max: null
  host: '0.0.0.0'
  port: 0
  env: {}

  worker-template-path: null

  worker-template: {}
    # kind: Pod
    # metadata:
    #   labels:
    #     foo: bar
    #     baz: quux
    # spec:
    #   restartPolicy: Never
    #   containers:
    #   - image: daskdev/dask:latest
    #     args:
    #       - dask-worker
    #       - --nthreads
    #       - '2'
    #       - --no-bokeh
    #       - --memory-limit
    #       - 6GB
    #       - --death-timeout
    #       - '60'
    #     resources:
    #       limits:
    #         cpu: "1.75"
    #         memory: 6G
    #       requests:
    #         cpu: "1.75"
    #         memory: 6G
```

So one solution would be to just not use worker-spec.yaml, and instead put the worker spec into dask's proper configuration system.
